import { Achievement } from '@/types/game';

export const MASTER_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-step',
    title: 'First Steps in Faith',
    description: 'Answer your first Bible question correctly.',
    icon: 'Sparkles',
    category: 'mastery',
    tier: 'bronze',
    target: 1,
    unlocked: false,
    xpReward: 100,
    coinReward: 50,
  },
  {
    id: 'ach-streak-5',
    title: 'Holy Fire',
    description: 'Achieve a streak of 5 correct answers in a row.',
    icon: 'Flame',
    category: 'streak',
    tier: 'bronze',
    target: 5,
    unlocked: false,
    xpReward: 200,
    coinReward: 75,
  },
  {
    id: 'ach-streak-10',
    title: 'Unquenchable Flame',
    description: 'Achieve a streak of 10 correct answers in a row.',
    icon: 'Zap',
    category: 'streak',
    tier: 'silver',
    target: 10,
    unlocked: false,
    xpReward: 500,
    coinReward: 150,
  },
  {
    id: 'ach-streak-25',
    title: 'Pillar of Fire',
    description: 'Achieve a legendary streak of 25 correct answers in a row.',
    icon: 'Flame',
    category: 'streak',
    tier: 'diamond',
    target: 25,
    unlocked: false,
    xpReward: 1500,
    coinReward: 500,
  },
  {
    id: 'ach-scripture-explorer',
    title: 'Scripture Explorer',
    description: 'Answer 50 total Bible questions.',
    icon: 'Compass',
    category: 'dedication',
    tier: 'bronze',
    target: 50,
    unlocked: false,
    xpReward: 300,
    coinReward: 100,
  },
  {
    id: 'ach-bible-scholar',
    title: 'Berean Scholar',
    description: 'Answer 200 total Bible questions with 85%+ accuracy.',
    icon: 'BookOpen',
    category: 'accuracy',
    tier: 'gold',
    target: 200,
    unlocked: false,
    xpReward: 1000,
    coinReward: 300,
  },
  {
    id: 'ach-speed-demon',
    title: 'Swift Messenger',
    description: 'Answer 10 questions in under 5 seconds each.',
    icon: 'Zap',
    category: 'speed',
    tier: 'silver',
    target: 10,
    unlocked: false,
    xpReward: 400,
    coinReward: 120,
  },
  {
    id: 'ach-perfect-round',
    title: 'Flawless Scribe',
    description: 'Complete any stage with 100% 3-star accuracy.',
    icon: 'CheckCircle2',
    category: 'accuracy',
    tier: 'silver',
    target: 1,
    unlocked: false,
    xpReward: 350,
    coinReward: 100,
  },
  {
    id: 'ach-daily-devotion',
    title: 'Faithful Daily Walk',
    description: 'Complete 3 Daily Bible Challenges.',
    icon: 'Calendar',
    category: 'dedication',
    tier: 'bronze',
    target: 3,
    unlocked: false,
    xpReward: 500,
    coinReward: 150,
  },
  {
    id: 'ach-daily-streak-7',
    title: 'Sabbath Keeper',
    description: 'Maintain a 7-day daily login streak.',
    icon: 'Sun',
    category: 'dedication',
    tier: 'gold',
    target: 7,
    unlocked: false,
    xpReward: 1000,
    coinReward: 400,
  },
  {
    id: 'ach-level-genesis',
    title: 'Overcomer of Genesis',
    description: 'Complete all stages in Level 1: The Beginning.',
    icon: 'Award',
    category: 'mastery',
    tier: 'silver',
    target: 1,
    unlocked: false,
    xpReward: 600,
    coinReward: 200,
  },
  {
    id: 'ach-level-gospels',
    title: 'Witness of Christ',
    description: 'Complete all stages in Level 6: The Life of Jesus.',
    icon: 'HeartHandshake',
    category: 'mastery',
    tier: 'gold',
    target: 1,
    unlocked: false,
    xpReward: 1200,
    coinReward: 350,
  },
  {
    id: 'ach-wisdom-hoarder',
    title: 'Treasure of Solomon',
    description: 'Accumulate 1,000 Wisdom Coins.',
    icon: 'Coins',
    category: 'dedication',
    tier: 'gold',
    target: 1000,
    unlocked: false,
    xpReward: 800,
    coinReward: 250,
  },
  {
    id: 'ach-word-master',
    title: 'CROWN OF THE WORD MASTER',
    description: 'Unlock and conquer the final Apex Stage of Level 10.',
    icon: 'Crown',
    category: 'mastery',
    tier: 'diamond',
    target: 1,
    unlocked: false,
    xpReward: 5000,
    coinReward: 2000,
  },
];
