import { CodexEntry } from '@/types/game';

export const MASTER_CODEX: CodexEntry[] = [
  {
    id: 'codex-creation-eden',
    title: 'The Garden of Eden & The Tree of Life',
    subtitle: 'Paradise, Original Fellowship & The Protoevangelium',
    era: 'Creation Era',
    book: 'Genesis 1-3',
    icon: 'Sparkles',
    unlocked: true,
    summary: 'Eden represents holy sanctuary space where God walked with mankind in the cool of the day. Following the Fall, Genesis 3:15 delivers the first messianic prophecy (the Protoevangelium) foretelling that the Seed of the woman would crush the serpent’s head.',
    hebrewGreekInsight: 'The Hebrew word for "breath of life" is Nishmat Chayim (נִשְׁמַת חַיִּים), indicating personal divine intimacy breathed uniquely into Adam unlike any other creature.',
    archaeologyFact: 'The Tigris (Hiddekel) and Euphrates rivers mentioned in Genesis 2:14 remain prominent geographical landmarks in modern Iraq, pinpointing the historical cradle of ancient civilization.',
  },
  {
    id: 'codex-ark-covenant',
    title: 'The Ark of the Covenant & The Mercy Seat',
    subtitle: 'The Throne of the Invisible God',
    era: 'Exodus & Tabernacle (c. 1446 BC)',
    book: 'Exodus 25',
    icon: 'Crown',
    unlocked: false,
    summary: 'Constructed of acacia wood overlaid with pure gold, the Ark contained the stone tablets of the Ten Commandments, the golden pot of manna, and Aaron’s rod that budded. Above it rested the Kapporeth (Mercy Seat) flanked by golden Cherubim.',
    hebrewGreekInsight: 'The Mercy Seat in Hebrew is Kapporeth (כַּפֹּרֶת), directly linked to Kippur (atonement/covering), where the High Priest sprinkled blood once a year on Yom Kippur.',
    archaeologyFact: 'Acacia (Shittim) wood is extremely dense, insect-resistant, and impervious to water, making it the ideal desert timber for enduring centuries in the Tabernacle.',
  },
  {
    id: 'codex-dead-sea-scrolls',
    title: 'The Great Isaiah Scroll & Dead Sea Scrolls',
    subtitle: 'Qumran Cave 1 (1947 Discovery)',
    era: 'Intertestamental & Prophetic',
    book: 'Isaiah 1-66',
    icon: 'Scroll',
    unlocked: false,
    summary: 'Discovered in 1947 by Bedouin shepherds in the caves of Qumran, the Great Isaiah Scroll (1QIsa) is a 24-foot parchment roll containing the complete 66 chapters of Isaiah, dating back to c. 125 BC.',
    hebrewGreekInsight: 'Comparison between the Qumran Isaiah scroll (125 BC) and the Masoretic Text (900 AD) demonstrated over 99% word-for-word textual fidelity across more than 1,000 years of hand copying.',
    archaeologyFact: 'The scrolls were preserved in sealed terra cotta jars in the arid, pitch-dark microclimate of the Judean desert overlooking the Dead Sea.',
  },
  {
    id: 'codex-pool-siloam',
    title: 'The Pool of Siloam & Hezekiah’s Tunnel',
    subtitle: 'Water in the City of David',
    era: 'Monarchy to Gospels',
    book: '2 Kings 20, John 9',
    icon: 'BookOpen',
    unlocked: false,
    summary: 'King Hezekiah carved a 1,750-foot tunnel through solid bedrock under Jerusalem to channel water from the Gihon Spring into the Pool of Siloam to withstand the Assyrian siege. Centuries later, Jesus sent the blind man to wash in Siloam.',
    hebrewGreekInsight: 'John 9:7 notes that Siloam means "Sent" (Hebrew: Shiloach שִׁלֹחַ), typifying Christ as the One Sent by the Father to open the eyes of the blind.',
    archaeologyFact: 'In 2004, municipal workers repairing a sewer pipe in Jerusalem accidentally unearthed the grand stone steps of the original 1st-century Pool of Siloam.',
  },
  {
    id: 'codex-resurrection-empty-tomb',
    title: 'The Garden Tomb & The Empty Sepulcher',
    subtitle: 'He Is Risen Indeed',
    era: 'First Century AD',
    book: 'Matthew 28, John 20',
    icon: 'Sun',
    unlocked: false,
    summary: 'The bodily resurrection of Jesus Christ is the historical bedrock of the Christian faith. Over 500 witnesses beheld the risen Lord across 40 days prior to His glorious ascension from the Mount of Olives.',
    hebrewGreekInsight: 'The Greek word for resurrection is Anastasis (ἀνάστασις), literally "a standing up again", affirming real physical, bodily conquest over biological death.',
    archaeologyFact: 'Rolling stone family tombs cut into limestone cliffs with weeping chambers and burial troughs precisely mirror the gospel accounts of Joseph of Arimathea’s tomb.',
  },
];
