import { Level } from '@/types/game';

export const LEVELS_CONFIG: Level[] = [
  {
    id: 1,
    levelNumber: 1,
    title: 'The Beginning',
    theme: 'Creation & The Patriarchs',
    era: 'Creation to Egypt (c. 4000 - 1800 BC)',
    bookCoverage: 'Genesis',
    description: 'Explore the origin of the world, the dawn of mankind, the great flood, and the covenant with Abraham.',
    iconName: 'Sparkles',
    unlockLevelRequirement: 0,
    stages: [
      {
        id: '1-1',
        stageNumber: 1,
        title: 'Days of Creation',
        subtitle: 'Let There Be Light',
        description: 'Test your knowledge on the six days of creation and the day of rest.',
        gameMode: 'blitz',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 250,
        coinReward: 50,
      },
      {
        id: '1-2',
        stageNumber: 2,
        title: 'The Garden & The Fall',
        subtitle: 'Eden to Exile',
        description: 'Discover the events surrounding Adam, Eve, the Serpent, and the promise of redemption.',
        gameMode: 'who_am_i',
        difficulty: 'easy',
        questionCount: 4,
        requiredStarsToUnlock: 1,
        xpReward: 300,
        coinReward: 60,
      },
      {
        id: '1-3',
        stageNumber: 3,
        title: 'The Great Ark & Flood',
        subtitle: 'Faith on the Waters',
        description: 'Journey with Noah, the animals, and God’s covenant sign in the clouds.',
        gameMode: 'bible_or_not',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 3,
        xpReward: 350,
        coinReward: 70,
      },
      {
        id: '1-4',
        stageNumber: 4,
        title: 'Father of Nations',
        subtitle: 'Abraham’s Walk of Faith',
        description: 'Follow Abram’s calling from Ur, the covenant of stars, and Isaac’s birth.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 5,
        xpReward: 400,
        coinReward: 80,
      },
      {
        id: '1-5',
        stageNumber: 5,
        title: 'Isaac, Jacob & Esau',
        subtitle: 'The Blessing & The Wrestler',
        description: 'Examine the birthright, Jacob’s ladder, wrestling with God, and 12 sons.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 7,
        xpReward: 450,
        coinReward: 90,
      },
      {
        id: '1-6',
        stageNumber: 6,
        title: 'Joseph the Dreamer',
        subtitle: 'Pits to Palaces',
        description: 'Witness God turning what was meant for evil into sovereign good in Egypt.',
        gameMode: 'timeline',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 9,
        xpReward: 500,
        coinReward: 100,
      },
      {
        id: '1-7',
        stageNumber: 7,
        title: 'Patriarch Sorting',
        subtitle: 'People, Places & Covenants',
        description: 'Organize patriarchs, promises, and locations into their proper places.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 550,
        coinReward: 120,
      },
      {
        id: '1-8',
        stageNumber: 8,
        title: 'Genesis Master Challenge',
        subtitle: 'The Beginning Champion',
        description: 'Prove your comprehensive mastery over Genesis in this multi-format trial.',
        gameMode: 'blitz',
        difficulty: 'hard',
        questionCount: 8,
        requiredStarsToUnlock: 15,
        xpReward: 1000,
        coinReward: 250,
        isBossStage: true,
      },
    ],
  },
  {
    id: 2,
    levelNumber: 2,
    title: 'The Journey',
    theme: 'Exodus, Law & Wilderness',
    era: 'Egypt to Jordan (c. 1446 - 1406 BC)',
    bookCoverage: 'Exodus, Leviticus, Numbers, Deuteronomy',
    description: 'Follow Moses and the children of Israel out of Egyptian bondage, through the Red Sea, and across the desert.',
    iconName: 'Flame',
    unlockLevelRequirement: 1,
    stages: [
      {
        id: '2-1',
        stageNumber: 1,
        title: 'The Burning Bush',
        subtitle: 'I AM WHO I AM',
        description: 'Moses’s calling, Aaron, and the confrontation with Pharaoh.',
        gameMode: 'who_said_it',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 350,
        coinReward: 60,
      },
      {
        id: '2-2',
        stageNumber: 2,
        title: 'Plagues & Passover',
        subtitle: 'Judgment & Deliverance',
        description: 'The ten signs of God’s power and the night of the Passover lamb.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 400,
        coinReward: 70,
      },
      {
        id: '2-3',
        stageNumber: 3,
        title: 'Crossing the Red Sea',
        subtitle: 'The Waters Part',
        description: 'Miraculous deliverance and Miriam’s song of triumph.',
        gameMode: 'bible_or_not',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 4,
        xpReward: 420,
        coinReward: 80,
      },
      {
        id: '2-4',
        stageNumber: 4,
        title: 'Mount Sinai & The Ten Commandments',
        subtitle: 'The Covenant Law',
        description: 'The law given on stone tablets, the golden calf, and the covenant renewal.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 6,
        xpReward: 460,
        coinReward: 90,
      },
      {
        id: '2-5',
        stageNumber: 5,
        title: 'The Tabernacle in the Wilderness',
        subtitle: 'The Dwelling of God',
        description: 'The Ark of the Covenant, the Holy of Holies, the priests, and the cloud of glory.',
        gameMode: 'who_am_i',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 8,
        xpReward: 500,
        coinReward: 100,
      },
      {
        id: '2-6',
        stageNumber: 6,
        title: 'Exodus Timeline',
        subtitle: 'Chronology of Freedom',
        description: 'Arrange key events from the river Nile to Mount Nebo in exact sequence.',
        gameMode: 'timeline',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 11,
        xpReward: 550,
        coinReward: 120,
      },
      {
        id: '2-7',
        stageNumber: 7,
        title: 'Wilderness Sorting',
        subtitle: 'Feasts, Sacrifices & Tribes',
        description: 'Sort feasts, offerings, and wilderness events into their rightful categories.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 13,
        xpReward: 600,
        coinReward: 130,
      },
      {
        id: '2-8',
        stageNumber: 8,
        title: 'Wilderness Master Challenge',
        subtitle: 'Overcomer of the Desert',
        description: 'Complete the ultimate test of the Torah and Exodus journey.',
        gameMode: 'blitz',
        difficulty: 'hard',
        questionCount: 8,
        requiredStarsToUnlock: 16,
        xpReward: 1200,
        coinReward: 300,
        isBossStage: true,
      },
    ],
  },
  {
    id: 3,
    levelNumber: 3,
    title: 'Kings & Kingdoms',
    theme: 'Judges, Kings & Chronicles',
    era: 'Conquest to Exile (c. 1400 - 586 BC)',
    bookCoverage: 'Joshua, Judges, 1 & 2 Samuel, 1 & 2 Kings, 1 & 2 Chronicles',
    description: 'From the fall of Jericho and courage of Gideon to the golden age of David and Solomon.',
    iconName: 'Crown',
    unlockLevelRequirement: 2,
    stages: [
      {
        id: '3-1',
        stageNumber: 1,
        title: 'Conquest & Judges',
        subtitle: 'Joshua, Deborah & Gideon',
        description: 'Jericho’s walls, Samson’s strength, and God raising deliverers.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 450,
        coinReward: 80,
      },
      {
        id: '3-2',
        stageNumber: 2,
        title: 'The Anointed Shepherd',
        subtitle: 'David & Goliath',
        description: 'A man after God’s own heart, the sling and stone, and fleeing Saul.',
        gameMode: 'who_am_i',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 2,
        xpReward: 480,
        coinReward: 85,
      },
      {
        id: '3-3',
        stageNumber: 3,
        title: 'Wisdom & The Temple',
        subtitle: 'King Solomon’s Reign',
        description: 'The prayer for wisdom, the Queen of Sheba, and the building of the temple.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 4,
        xpReward: 520,
        coinReward: 95,
      },
      {
        id: '3-4',
        stageNumber: 4,
        title: 'The Kingdom Divided',
        subtitle: 'Israel & Judah',
        description: 'Rehoboam, Jeroboam, and the split into Northern and Southern kingdoms.',
        gameMode: 'bible_or_not',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 7,
        xpReward: 550,
        coinReward: 105,
      },
      {
        id: '3-5',
        stageNumber: 5,
        title: 'Fire on Mount Carmel',
        subtitle: 'Elijah & Elisha',
        description: 'Confronting prophets of Baal, the still small voice, and the chariot of fire.',
        gameMode: 'who_said_it',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 9,
        xpReward: 580,
        coinReward: 115,
      },
      {
        id: '3-6',
        stageNumber: 6,
        title: 'Kingdoms Timeline',
        subtitle: 'Dynasties & Falls',
        description: 'Order the major coronations, battles, and falls of Samaria and Jerusalem.',
        gameMode: 'timeline',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 620,
        coinReward: 130,
      },
      {
        id: '3-7',
        stageNumber: 7,
        title: 'Kings of Judah vs Israel',
        subtitle: 'Righteous & Wicked Rulers',
        description: 'Classify good kings (Hezekiah, Josiah) and bad kings (Ahab, Manasseh).',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 14,
        xpReward: 650,
        coinReward: 140,
      },
      {
        id: '3-8',
        stageNumber: 8,
        title: 'Monarchy Crown Trial',
        subtitle: 'Master of Kings',
        description: 'The supreme royal test across the historical books of Scripture.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 17,
        xpReward: 1350,
        coinReward: 350,
        isBossStage: true,
      },
    ],
  },
  {
    id: 4,
    levelNumber: 4,
    title: 'Voices of the Prophets',
    theme: 'Major & Minor Prophets',
    era: 'Prophetic Warnings & Messianic Hope (c. 800 - 400 BC)',
    bookCoverage: 'Isaiah to Malachi',
    description: 'Hear the thunderous proclamations of repentance and the glorious promises of the coming Messiah.',
    iconName: 'Scroll',
    unlockLevelRequirement: 3,
    stages: [
      {
        id: '4-1',
        stageNumber: 1,
        title: 'The Prince of Prophets',
        subtitle: 'Isaiah’s Holy Vision',
        description: 'The suffering servant, Emmanuel prophecy, and the train of His robe filling the temple.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 500,
        coinReward: 90,
      },
      {
        id: '4-2',
        stageNumber: 2,
        title: 'The Weeping Prophet',
        subtitle: 'Jeremiah & The New Covenant',
        description: 'The potter’s wheel, the yoke, the letter to exiles, and the covenant written on hearts.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 520,
        coinReward: 95,
      },
      {
        id: '4-3',
        stageNumber: 3,
        title: 'Visions of Glory & Dry Bones',
        subtitle: 'Ezekiel’s Calling',
        description: 'The four living creatures, the valley of dry bones, and the river flowing from the temple.',
        gameMode: 'who_am_i',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 4,
        xpReward: 560,
        coinReward: 105,
      },
      {
        id: '4-4',
        stageNumber: 4,
        title: 'Faith in Babylon',
        subtitle: 'Daniel, Lions & The Fiery Furnace',
        description: 'Shadrach, Meshach, Abednego, handwriting on the wall, and visions of four kingdoms.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 7,
        xpReward: 600,
        coinReward: 110,
      },
      {
        id: '4-5',
        stageNumber: 5,
        title: 'The Twelve Minor Prophets',
        subtitle: 'Hosea to Malachi',
        description: 'Jonah in Nineveh, Micah’s Bethlehem prophecy, and Habakkuk’s prayer of trust.',
        gameMode: 'bible_or_not',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 9,
        xpReward: 640,
        coinReward: 120,
      },
      {
        id: '4-6',
        stageNumber: 6,
        title: 'Messianic Prophecy Timeline',
        subtitle: 'From Seed to Bethlehem',
        description: 'Sequence the prophetic milestones foretelling Christ’s birth, death, and reign.',
        gameMode: 'timeline',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 680,
        coinReward: 135,
      },
      {
        id: '4-7',
        stageNumber: 7,
        title: 'Major vs Minor Prophets Sort',
        subtitle: 'Discerning the Messengers',
        description: 'Sort the prophetic writings and destinations (Judah, Israel, foreign nations).',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 14,
        xpReward: 720,
        coinReward: 145,
      },
      {
        id: '4-8',
        stageNumber: 8,
        title: 'Prophetic Grand Master Trial',
        subtitle: 'Seer of Truth',
        description: 'Master all prophecies and visions in this high-intensity test.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 17,
        xpReward: 1500,
        coinReward: 400,
        isBossStage: true,
      },
    ],
  },
  {
    id: 5,
    levelNumber: 5,
    title: 'Wisdom & Praise',
    theme: 'Poetic & Wisdom Books',
    era: 'Timeless Biblical Poetry',
    bookCoverage: 'Job, Psalms, Proverbs, Ecclesiastes, Song of Solomon',
    description: 'Drink from the deep wells of Davidic worship, Solomonic proverbs, and Job’s steadfast faith.',
    iconName: 'BookOpen',
    unlockLevelRequirement: 4,
    stages: [
      {
        id: '5-1',
        stageNumber: 1,
        title: 'The Shepherd’s Psalm',
        subtitle: 'Psalm 23 & Hymns of Praise',
        description: 'Green pastures, still waters, valleys of the shadow of death, and everlasting goodness.',
        gameMode: 'verse_match',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 500,
        coinReward: 90,
      },
      {
        id: '5-2',
        stageNumber: 2,
        title: 'Proverbs of Insight',
        subtitle: 'The Fear of the Lord',
        description: 'Paths of righteousness, guarding your heart, and the wise tongue.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 530,
        coinReward: 95,
      },
      {
        id: '5-3',
        stageNumber: 3,
        title: 'The Trial of Job',
        subtitle: 'I Know My Redeemer Lives',
        description: 'Testing of righteous Job, counsel of his friends, and God answering from the whirlwind.',
        gameMode: 'who_am_i',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 4,
        xpReward: 560,
        coinReward: 100,
      },
      {
        id: '5-4',
        stageNumber: 4,
        title: 'A Time for Everything',
        subtitle: 'Ecclesiastes & Song of Songs',
        description: 'The search for meaning under the sun, seasons of life, and pure love.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 7,
        xpReward: 600,
        coinReward: 110,
      },
      {
        id: '5-5',
        stageNumber: 5,
        title: 'Proverbs: Biblical vs Cultural',
        subtitle: 'Fact or Fiction in Wisdom',
        description: 'Spot which phrases are actual Scripture versus popular secular sayings.',
        gameMode: 'bible_or_not',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 9,
        xpReward: 640,
        coinReward: 120,
      },
      {
        id: '5-6',
        stageNumber: 6,
        title: 'Psalm Types Sorting',
        subtitle: 'Lament, Praise & Messianic',
        description: 'Categorize famous Psalms into royal, thanksgiving, repentance, and wisdom psalms.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 680,
        coinReward: 135,
      },
      {
        id: '5-7',
        stageNumber: 7,
        title: 'Wisdom Grand Master',
        subtitle: 'Sage of Scripture',
        description: 'The comprehensive test of the five poetic books of the Old Testament.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 15,
        xpReward: 1600,
        coinReward: 420,
        isBossStage: true,
      },
    ],
  },
  {
    id: 6,
    levelNumber: 6,
    title: 'The Life of Jesus',
    theme: 'The Four Gospels',
    era: 'The Incarnation & Ministry (c. 4 BC - 33 AD)',
    bookCoverage: 'Matthew, Mark, Luke, John',
    description: 'Walk in the footsteps of Christ: His virgin birth, mighty miracles, transformative parables, cross, and empty tomb.',
    iconName: 'Sun',
    unlockLevelRequirement: 5,
    stages: [
      {
        id: '6-1',
        stageNumber: 1,
        title: 'The Nativity & Early Years',
        subtitle: 'Unto Us a Savior',
        description: 'Bethlehem, the star, the shepherds, wise men, and the presentation in the Temple.',
        gameMode: 'blitz',
        difficulty: 'easy',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 550,
        coinReward: 100,
      },
      {
        id: '6-2',
        stageNumber: 2,
        title: 'Baptism & Temptation',
        subtitle: 'The Beloved Son in the Wilderness',
        description: 'John the Baptist, the voice from heaven, and overcoming the devil with Scripture.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 580,
        coinReward: 105,
      },
      {
        id: '6-3',
        stageNumber: 3,
        title: 'The Sermon on the Mount',
        subtitle: 'The Beatitudes & Kingdom Ethics',
        description: 'Salt and light, loving enemies, the Lord’s Prayer, and building on the rock.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 4,
        xpReward: 620,
        coinReward: 115,
      },
      {
        id: '6-4',
        stageNumber: 4,
        title: 'Miracles of Authority',
        subtitle: 'Calming Storms & Raising the Dead',
        description: 'Lazarus, walking on water, feeding the 5,000, and healing the blind.',
        gameMode: 'who_am_i',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 7,
        xpReward: 660,
        coinReward: 125,
      },
      {
        id: '6-5',
        stageNumber: 5,
        title: 'Parables of the Kingdom',
        subtitle: 'Hidden Treasures & The Prodigal Son',
        description: 'The Sower, the Good Samaritan, the Lost Sheep, and the Ten Virgins.',
        gameMode: 'bible_or_not',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 9,
        xpReward: 700,
        coinReward: 135,
      },
      {
        id: '6-6',
        stageNumber: 6,
        title: 'Passion Week Chronology',
        subtitle: 'From Palm Sunday to the Empty Tomb',
        description: 'Triumphal entry, Last Supper, Gethsemane, trials, Crucifixion, and Resurrection.',
        gameMode: 'timeline',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 750,
        coinReward: 150,
      },
      {
        id: '6-7',
        stageNumber: 7,
        title: 'Gospel Authors & Audiences',
        subtitle: 'Lion, Ox, Man & Eagle',
        description: 'Sort distinctive features of Matthew, Mark, Luke, and John.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 14,
        xpReward: 800,
        coinReward: 160,
      },
      {
        id: '6-8',
        stageNumber: 8,
        title: 'Gospel Master Challenge',
        subtitle: 'Witness of the Risen King',
        description: 'The ultimate synthesis test on the earthly life and teachings of Jesus Christ.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 17,
        xpReward: 1800,
        coinReward: 500,
        isBossStage: true,
      },
    ],
  },
  {
    id: 7,
    levelNumber: 7,
    title: 'The Early Church',
    theme: 'Acts of the Apostles',
    era: 'Jerusalem to Rome (c. 33 - 62 AD)',
    bookCoverage: 'Acts of the Apostles',
    description: 'The outpouring of the Holy Spirit at Pentecost, the bold witness of Peter, Stephen’s martyrdom, and Paul’s missionary journeys.',
    iconName: 'Flame',
    unlockLevelRequirement: 6,
    stages: [
      {
        id: '7-1',
        stageNumber: 1,
        title: 'Pentecost & Power',
        subtitle: 'Tongues of Fire',
        description: 'Ascension, Matthias chosen, the rushing wind, Peter’s sermon, and 3,000 saved.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 600,
        coinReward: 110,
      },
      {
        id: '7-2',
        stageNumber: 2,
        title: 'The First Martyrs & Deacons',
        subtitle: 'Stephen & Philip',
        description: 'Stephen’s defense before the Sanhedrin, Philip and the Ethiopian eunuch.',
        gameMode: 'who_am_i',
        difficulty: 'medium',
        questionCount: 4,
        requiredStarsToUnlock: 2,
        xpReward: 640,
        coinReward: 120,
      },
      {
        id: '7-3',
        stageNumber: 3,
        title: 'The Damascus Road',
        subtitle: 'Saul Becomes Paul',
        description: 'Blinding light, Ananias in Damascus, escape in a basket over the wall.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 4,
        xpReward: 680,
        coinReward: 130,
      },
      {
        id: '7-4',
        stageNumber: 4,
        title: 'Gospel to the Gentiles',
        subtitle: 'Cornelius & Antioch',
        description: 'Peter’s rooftop vision, believers first called Christians in Antioch, and Peter freed from prison.',
        gameMode: 'verse_match',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 7,
        xpReward: 720,
        coinReward: 140,
      },
      {
        id: '7-5',
        stageNumber: 5,
        title: 'Missionary Journeys Timeline',
        subtitle: 'From Antioch to Rome',
        description: 'Order Paul’s epic journeys, shipwrecks, riots in Ephesus, and arrest in Jerusalem.',
        gameMode: 'timeline',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 10,
        xpReward: 760,
        coinReward: 150,
      },
      {
        id: '7-6',
        stageNumber: 6,
        title: 'Acts Companions & Cities',
        subtitle: 'Barnabas, Silas, Timothy & Luke',
        description: 'Sort early church leaders, mission partners, and key cities into their regions.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 800,
        coinReward: 165,
      },
      {
        id: '7-7',
        stageNumber: 7,
        title: 'Acts Grand Champion',
        subtitle: 'Apostolic Trailblazer',
        description: 'Comprehensive trial on the explosion of the early church.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 15,
        xpReward: 2000,
        coinReward: 550,
        isBossStage: true,
      },
    ],
  },
  {
    id: 8,
    levelNumber: 8,
    title: 'Letters of Faith',
    theme: 'The Epistles',
    era: 'Apostolic Doctrine & Church Life (c. 48 - 95 AD)',
    bookCoverage: 'Romans to Jude',
    description: 'Master the doctrines of grace, justification by faith, the armor of God, the fruit of the Spirit, and practical Christian living.',
    iconName: 'Mail',
    unlockLevelRequirement: 7,
    stages: [
      {
        id: '8-1',
        stageNumber: 1,
        title: 'The Fortress of Romans',
        subtitle: 'Justification by Grace',
        description: 'Romans 8, no condemnation, more than conquerors, and the Romans Road.',
        gameMode: 'verse_match',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 650,
        coinReward: 120,
      },
      {
        id: '8-2',
        stageNumber: 2,
        title: 'The Way of Love & The Spirit',
        subtitle: 'Corinthians & Galatians',
        description: '1 Corinthians 13, the spiritual gifts, the resurrection chapter, and the Fruit of the Spirit.',
        gameMode: 'blitz',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 700,
        coinReward: 130,
      },
      {
        id: '8-3',
        stageNumber: 3,
        title: 'The Armor of God & Joy',
        subtitle: 'Ephesians & Philippians',
        description: 'Saved by grace through faith, spiritual warfare, rejoicing always, and pressing toward the prize.',
        gameMode: 'who_said_it',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 5,
        xpReward: 750,
        coinReward: 140,
      },
      {
        id: '8-4',
        stageNumber: 4,
        title: 'The Superiority of Christ',
        subtitle: 'The Epistle to the Hebrews',
        description: 'The Great High Priest, the Hall of Faith (Hebrews 11), and looking unto Jesus.',
        gameMode: 'who_am_i',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 8,
        xpReward: 800,
        coinReward: 155,
      },
      {
        id: '8-5',
        stageNumber: 5,
        title: 'Epistle Quotes: Biblical or Not?',
        subtitle: 'Discerning Scripture from Tradition',
        description: 'Examine theological statements and verify if they are chapter & verse truth.',
        gameMode: 'bible_or_not',
        difficulty: 'expert',
        questionCount: 5,
        requiredStarsToUnlock: 10,
        xpReward: 850,
        coinReward: 170,
      },
      {
        id: '8-6',
        stageNumber: 6,
        title: 'Pauline vs General Epistles',
        subtitle: 'Sort the Letters',
        description: 'Sort the 21 New Testament epistles by author, recipients, and main themes.',
        gameMode: 'sort',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 900,
        coinReward: 180,
      },
      {
        id: '8-7',
        stageNumber: 7,
        title: 'Epistles Master Trial',
        subtitle: 'Scholar of the Epistles',
        description: 'The supreme test of New Testament theology and pastoral wisdom.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 15,
        xpReward: 2200,
        coinReward: 600,
        isBossStage: true,
      },
    ],
  },
  {
    id: 9,
    levelNumber: 9,
    title: 'The Revelation',
    theme: 'Apocalypse & Victorious Hope',
    era: 'The End of the Age & Eternity',
    bookCoverage: 'Revelation',
    description: 'The revelation of Jesus Christ given to John on Patmos: the seven churches, the Lamb on the throne, the final victory, and the New Jerusalem.',
    iconName: 'ShieldAlert',
    unlockLevelRequirement: 8,
    stages: [
      {
        id: '9-1',
        stageNumber: 1,
        title: 'The Seven Churches of Asia',
        subtitle: 'Ephesus to Laodicea',
        description: 'First love, the crown of life, lukewarmness, and standing at the door knocking.',
        gameMode: 'who_said_it',
        difficulty: 'medium',
        questionCount: 5,
        requiredStarsToUnlock: 0,
        xpReward: 750,
        coinReward: 140,
      },
      {
        id: '9-2',
        stageNumber: 2,
        title: 'The Heavenly Throne & The Lamb',
        subtitle: 'Worthy Is the Lamb',
        description: 'The rainbow circle, twenty-four elders, the sea of glass, and the scroll with seven seals.',
        gameMode: 'verse_match',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 2,
        xpReward: 800,
        coinReward: 155,
      },
      {
        id: '9-3',
        stageNumber: 3,
        title: 'Seals, Trumpets & Bowls',
        subtitle: 'Cosmic Judgments & The Two Witnesses',
        description: 'The four horsemen, the silence in heaven, and the victorious 144,000.',
        gameMode: 'blitz',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 5,
        xpReward: 850,
        coinReward: 170,
      },
      {
        id: '9-4',
        stageNumber: 4,
        title: 'The Rider on the White Horse',
        subtitle: 'King of Kings & Lord of Lords',
        description: 'The marriage supper of the Lamb, the final battle, and the casting down of the adversary.',
        gameMode: 'who_am_i',
        difficulty: 'hard',
        questionCount: 4,
        requiredStarsToUnlock: 8,
        xpReward: 900,
        coinReward: 185,
      },
      {
        id: '9-5',
        stageNumber: 5,
        title: 'The New Heaven & New Earth',
        subtitle: 'No More Tears, Death, or Sorrow',
        description: 'The New Jerusalem descending, streets of gold, river of life, and tree of life.',
        gameMode: 'verse_match',
        difficulty: 'hard',
        questionCount: 5,
        requiredStarsToUnlock: 10,
        xpReward: 950,
        coinReward: 200,
      },
      {
        id: '9-6',
        stageNumber: 6,
        title: 'Revelation Symbols Sort',
        subtitle: 'Lampstands, Stars & Scrolls',
        description: 'Categorize symbols, visions, and promises to the overcomers.',
        gameMode: 'sort',
        difficulty: 'expert',
        questionCount: 4,
        requiredStarsToUnlock: 12,
        xpReward: 1000,
        coinReward: 220,
      },
      {
        id: '9-7',
        stageNumber: 7,
        title: 'Revelation Grand Finale',
        subtitle: 'Master of Prophecy',
        description: 'Conquer the final book of the Bible with unmatched precision.',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 8,
        requiredStarsToUnlock: 15,
        xpReward: 2500,
        coinReward: 700,
        isBossStage: true,
      },
    ],
  },
  {
    id: 10,
    levelNumber: 10,
    title: 'WORD MASTER',
    theme: 'Ultimate Scripture Quest',
    era: 'Genesis to Revelation',
    bookCoverage: 'All 66 Books of the Bible',
    description: 'The ultimate summit of biblical knowledge. Test your mastery across all eras, covenants, characters, verses, and doctrines.',
    iconName: 'Trophy',
    unlockLevelRequirement: 9,
    stages: [
      {
        id: '10-1',
        stageNumber: 1,
        title: 'The Great Old Testament Gauntlet',
        subtitle: 'Law, History & Prophets',
        description: 'Lightning round of deep Old Testament knowledge.',
        gameMode: 'blitz',
        difficulty: 'hard',
        questionCount: 6,
        requiredStarsToUnlock: 0,
        xpReward: 1000,
        coinReward: 200,
      },
      {
        id: '10-2',
        stageNumber: 2,
        title: 'The New Covenant Gauntlet',
        subtitle: 'Gospels, Acts & Epistles',
        description: 'High-speed trial across Christ’s teachings and apostolic epistles.',
        gameMode: 'blitz',
        difficulty: 'hard',
        questionCount: 6,
        requiredStarsToUnlock: 2,
        xpReward: 1100,
        coinReward: 220,
      },
      {
        id: '10-3',
        stageNumber: 3,
        title: 'Master of Verses',
        subtitle: 'Complete the Greatest Scriptures',
        description: 'Precision memory verses across all 66 books.',
        gameMode: 'verse_match',
        difficulty: 'expert',
        questionCount: 6,
        requiredStarsToUnlock: 5,
        xpReward: 1200,
        coinReward: 250,
      },
      {
        id: '10-4',
        stageNumber: 4,
        title: 'Grand Biblical Timeline',
        subtitle: 'From Eternity to Eternity',
        description: 'Sequence the overarching redemptive plan of God.',
        gameMode: 'timeline',
        difficulty: 'expert',
        questionCount: 5,
        requiredStarsToUnlock: 8,
        xpReward: 1400,
        coinReward: 300,
      },
      {
        id: '10-5',
        stageNumber: 5,
        title: 'The Sovereign Bible Sort',
        subtitle: 'The 66 Books Matrix',
        description: 'Sort books by literary genre (Pentateuch, Historical, Poetic, Major Prophets, Gospels, Epistles).',
        gameMode: 'sort',
        difficulty: 'expert',
        questionCount: 5,
        requiredStarsToUnlock: 11,
        xpReward: 1600,
        coinReward: 350,
      },
      {
        id: '10-6',
        stageNumber: 6,
        title: 'THE WORD MASTER APEX',
        subtitle: 'Crown of the Word Champion',
        description: 'The supreme test of 10 multi-discipline questions. Complete this to claim the eternal Word Master mantle!',
        gameMode: 'blitz',
        difficulty: 'expert',
        questionCount: 10,
        requiredStarsToUnlock: 14,
        xpReward: 5000,
        coinReward: 1500,
        isBossStage: true,
      },
    ],
  },
];
