import { Question } from '@/types/game';

export const MASTER_QUESTIONS: Question[] = [
  // ==========================================
  // LEVEL 1: THE BEGINNING (GENESIS)
  // ==========================================
  {
    id: 'gen-001',
    question: 'On which day of creation did God create the sun, moon, and stars to separate day from night and mark seasons, days, and years?',
    type: 'multiple_choice',
    options: ['Day 1', 'Day 3', 'Day 4', 'Day 6'],
    correctAnswer: 'Day 4',
    explanation: 'On the fourth day, God made two great lights—the greater light to govern the day and the lesser light to govern the night—and also the stars.',
    reference: 'Genesis 1:14-19',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 1,
    timeLimit: 15,
    xpReward: 100,
    points: 100,
    tags: ['creation', 'genesis', 'days'],
  },
  {
    id: 'gen-002',
    question: 'What was the first thing God created on Day 1?',
    type: 'multiple_choice',
    options: ['Light', 'Land and Vegetation', 'Sun and Moon', 'Birds and Fish'],
    correctAnswer: 'Light',
    explanation: 'God said, "Let there be light," and there was light. God saw that the light was good, and separated the light from darkness.',
    reference: 'Genesis 1:3-5',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 1,
    timeLimit: 15,
    xpReward: 100,
    points: 100,
    tags: ['creation', 'genesis', 'day1'],
  },
  {
    id: 'gen-003',
    question: 'What did God do on the seventh day after completing the creation of heavens and earth?',
    type: 'multiple_choice',
    options: ['Created the angels', 'Rested and made it holy', 'Planted the Garden of Eden', 'Created the oceans'],
    correctAnswer: 'Rested and made it holy',
    explanation: 'By the seventh day God had finished the work he had been doing; so on the seventh day he rested from all his work and blessed it.',
    reference: 'Genesis 2:2-3',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 1,
    timeLimit: 15,
    xpReward: 100,
    points: 100,
  },
  {
    id: 'gen-004',
    question: 'What kind of wood did God command Noah to use to build the ark?',
    type: 'multiple_choice',
    options: ['Cedar of Lebanon', 'Gopher wood (Cypress)', 'Acacia wood', 'Olive wood'],
    correctAnswer: 'Gopher wood (Cypress)',
    explanation: 'God told Noah: "Make yourself an ark of gopher wood; make rooms in it and coat it with pitch inside and out."',
    reference: 'Genesis 6:14',
    translation: 'ESV',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 1,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'gen-005',
    question: 'What was the sign of God’s covenant with Noah and every living creature that the waters would never again destroy all flesh?',
    type: 'multiple_choice',
    options: ['An olive branch', 'A rainbow in the clouds', 'An altar of stone', 'A pillar of fire'],
    correctAnswer: 'A rainbow in the clouds',
    explanation: 'God said, "I have set my rainbow in the clouds, and it will be the sign of the covenant between me and the earth."',
    reference: 'Genesis 9:13',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 1,
    timeLimit: 15,
    xpReward: 100,
    points: 100,
  },
  // WHO AM I (Stage 1-2)
  {
    id: 'who-001',
    question: 'Can you deduce which biblical figure is described below by their progressive clues?',
    type: 'clues',
    clues: [
      'I was born in Ur of the Chaldeans and left my homeland at age 75.',
      'God promised that through my offspring, all nations on earth would be blessed.',
      'My original name was changed to mean "Father of a multitude of nations."',
      'In faith, I obeyed God when called to offer my promised son Isaac on Mount Moriah.'
    ],
    options: ['Noah', 'Abraham', 'Jacob', 'Moses'],
    correctAnswer: 'Abraham',
    explanation: 'Abraham (originally Abram) answered God’s call in faith, leaving Haran for Canaan, and became known as the father of all who believe.',
    reference: 'Genesis 12:1-4, Genesis 17:5, Hebrews 11:8-19',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 2,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },
  {
    id: 'who-002',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was the mother of all living.',
      'I was formed from Adam’s rib in the Garden of Eden.',
      'The serpent deceived me into eating the fruit of the tree of the knowledge of good and evil.',
      'I gave birth to Cain, Abel, and Seth.'
    ],
    options: ['Sarah', 'Eve', 'Rachel', 'Rebekah'],
    correctAnswer: 'Eve',
    explanation: 'Eve was created by God as a suitable helper for Adam and was named Eve because she would become the mother of all living.',
    reference: 'Genesis 2:21-23, Genesis 3:20',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 2,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },
  {
    id: 'who-003',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was the favorite son of Jacob, given an ornate, richly ornamented robe.',
      'I had prophetic dreams about the sun, moon, and eleven stars bowing down to me.',
      'My jealous brothers threw me into a cistern and sold me into slavery in Egypt.',
      'I interpreted Pharaoh’s dreams of seven fat and lean cows and rose to become Prime Minister of Egypt.'
    ],
    options: ['Benjamin', 'Joseph', 'Judah', 'Joshua'],
    correctAnswer: 'Joseph',
    explanation: 'Joseph endured betrayal and imprisonment before God elevated him in Egypt to preserve many lives during the great famine.',
    reference: 'Genesis 37:3, Genesis 41:39-44, Genesis 50:20',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 2,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },
  {
    id: 'who-004',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was a twin who came out grasping my brother’s heel.',
      'I bought my brother’s birthright for a bowl of red lentil stew.',
      'I dreamed of a stairway resting on earth with its top reaching to heaven and angels ascending and descending.',
      'After wrestling with God all night at Peniel, my name was changed to Israel.'
    ],
    options: ['Esau', 'Jacob', 'Isaac', 'Laban'],
    correctAnswer: 'Jacob',
    explanation: 'Jacob, son of Isaac and Rebekah, was given the name Israel ("he struggles with God") and became the father of the 12 tribes.',
    reference: 'Genesis 25:26, Genesis 28:12, Genesis 32:28',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 2,
    timeLimit: 25,
    xpReward: 160,
    points: 160,
  },
  // BIBLE OR NOT (Stage 1-3)
  {
    id: 'bon-001',
    question: 'Is this statement actually found in the Bible?\n\n"The forbidden fruit that Eve ate in the Garden of Eden was an apple."',
    type: 'true_false',
    correctAnswer: false,
    explanation: 'The Bible never specifies an apple! Genesis 3:6 simply calls it "the fruit of the tree that is in the middle of the garden." The apple tradition arose centuries later in Western art and Latin wordplay (malum = apple / evil).',
    reference: 'Genesis 3:1-6',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 3,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'bon-002',
    question: 'Is this statement actually in the Bible?\n\n"God brought two of every kind of animal, male and female, into Noah’s ark, but for clean animals and birds, seven pairs were taken."',
    type: 'true_false',
    correctAnswer: true,
    explanation: 'Yes! While two of every unclean animal were taken, Genesis 7:2-3 specifically commands taking seven pairs of every clean animal and bird for sacrifices and repopulation.',
    reference: 'Genesis 7:2-3',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 3,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'bon-003',
    question: 'Is this statement actually in the Bible?\n\n"God helps those who help themselves."',
    type: 'true_false',
    correctAnswer: false,
    explanation: 'This famous proverb is NOT in the Bible! It originated in ancient Greek fables (Aesop) and was popularized by Benjamin Franklin in Poor Richard’s Almanack. The Bible teaches that God saves and helps the helpless who trust in Him.',
    reference: 'Romans 5:6, Psalm 121:1-2',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Wisdom',
    level: 1,
    stage: 3,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'bon-004',
    question: 'Is this statement actually in the Bible?\n\n"Methuselah lived 969 years, making him the longest-lived human recorded in Scripture."',
    type: 'true_false',
    correctAnswer: true,
    explanation: 'True! Genesis 5:27 records: "Altogether, Methuselah lived a total of 969 years, and then he died."',
    reference: 'Genesis 5:27',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 3,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'bon-005',
    question: 'Is this statement actually in the Bible?\n\n"Money is the root of all evil."',
    type: 'true_false',
    correctAnswer: false,
    explanation: 'Common misquote! 1 Timothy 6:10 states that "the LOVE of money is a root of all kinds of evil," not money itself.',
    reference: '1 Timothy 6:10',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Epistles',
    level: 1,
    stage: 3,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  // COMPLETE THE VERSE (Stage 1-4)
  {
    id: 'ver-001',
    question: 'Complete this foundational verse:\n\n"In the beginning, God created the ___ and the ___."',
    type: 'fill_blank',
    options: ['heavens; earth', 'sun; moon', 'angels; universe', 'seas; dry land'],
    correctAnswer: 'heavens; earth',
    explanation: '"In the beginning God created the heavens and the earth." — Genesis 1:1',
    reference: 'Genesis 1:1',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 4,
    timeLimit: 20,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'ver-002',
    question: 'Complete the covenant promise to Abram:\n\n"Look up at the sky and count the ___ — if indeed you can count them... So shall your offspring be."',
    type: 'fill_blank',
    options: ['clouds', 'stars', 'birds', 'sands'],
    correctAnswer: 'stars',
    explanation: 'He took him outside and said, "Look up at the sky and count the stars—if indeed you can count them." Then he said to him, "So shall your offspring be." — Genesis 15:5',
    reference: 'Genesis 15:5',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 4,
    timeLimit: 20,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'ver-003',
    question: 'Complete Joseph’s profound declaration to his brothers:\n\n"You intended to harm me, but God intended it for ___ to accomplish what is now being done, the saving of many lives."',
    type: 'fill_blank',
    options: ['justice', 'glory', 'good', 'peace'],
    correctAnswer: 'good',
    explanation: '"You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives." — Genesis 50:20',
    reference: 'Genesis 50:20',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 4,
    timeLimit: 20,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'ver-004',
    question: 'Complete the Lord’s word on human creation:\n\n"So God created mankind in his own ___, in the image of God he created them; male and female he created them."',
    type: 'fill_blank',
    options: ['image', 'power', 'glory', 'wisdom'],
    correctAnswer: 'image',
    explanation: '"So God created mankind in his own image, in the image of God he created them; male and female he created them." — Genesis 1:27',
    reference: 'Genesis 1:27',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Creation',
    level: 1,
    stage: 4,
    timeLimit: 20,
    xpReward: 130,
    points: 130,
  },
  // WHO SAID IT (Stage 1-5)
  {
    id: 'wsi-001',
    question: 'Who asked this famous defensive question after murdering his brother?\n\n"Am I my brother’s keeper?"',
    type: 'quote',
    options: ['Lamech', 'Cain', 'Esau', 'Absalom'],
    correctAnswer: 'Cain',
    explanation: 'Then the Lord said to Cain, "Where is your brother Abel?" "I don’t know," he replied. "Am I my brother’s keeper?"',
    reference: 'Genesis 4:9',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 5,
    timeLimit: 18,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'wsi-002',
    question: 'Who said this when God told her she would give birth to a son in her old age?\n\n"God has brought me laughter, and everyone who hears about this will laugh with me."',
    type: 'quote',
    options: ['Hagar', 'Sarah', 'Rebekah', 'Leah'],
    correctAnswer: 'Sarah',
    explanation: 'Sarah named her son Isaac (meaning "he laughs") and praised God for bringing joy in her old age.',
    reference: 'Genesis 21:6',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Women of the Bible',
    level: 1,
    stage: 5,
    timeLimit: 18,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'wsi-003',
    question: 'Who said this after awakening from his vision of the heavenly ladder?\n\n"Surely the Lord is in this place, and I was not aware of it... How awesome is this place! This is none other than the house of God; this is the gate of heaven."',
    type: 'quote',
    options: ['Abraham', 'Jacob', 'Isaac', 'Joseph'],
    correctAnswer: 'Jacob',
    explanation: 'Jacob set up the stone he had placed under his head as a pillar and poured oil on top of it, naming the place Bethel ("House of God").',
    reference: 'Genesis 28:16-19',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 5,
    timeLimit: 18,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'wsi-004',
    question: 'Who said this to his son Isaac on the way up Mount Moriah when asked where the lamb for the burnt offering was?\n\n"God himself will provide the lamb for the burnt offering, my son."',
    type: 'quote',
    options: ['Noah', 'Abraham', 'Melchizedek', 'Lot'],
    correctAnswer: 'Abraham',
    explanation: 'Abraham answered in prophetic faith, and indeed God provided a ram caught in a thicket by its horns.',
    reference: 'Genesis 22:7-8',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Patriarchs',
    level: 1,
    stage: 5,
    timeLimit: 18,
    xpReward: 130,
    points: 130,
  },
  // BIBLE TIMELINE (Stage 1-6)
  {
    id: 'time-001',
    question: 'Arrange these monumental Genesis events in correct chronological order:',
    type: 'timeline',
    timelineItems: [
      { id: 't1', title: 'God creates the heavens, earth, and mankind in Eden', order: 1 },
      { id: 't2', title: 'Noah builds the Ark and survives the Great Flood', order: 2 },
      { id: 't3', title: 'The building and dispersion at the Tower of Babel', order: 3 },
      { id: 't4', title: 'God calls Abraham to leave Ur of the Chaldeans', order: 4 },
      { id: 't5', title: 'Joseph becomes governor of Egypt and saves his family', order: 5 },
    ],
    correctAnswer: ['t1', 't2', 't3', 't4', 't5'],
    explanation: 'Genesis unfolds from Creation (Gen 1-2) → The Flood (Gen 6-9) → Babel (Gen 11) → The Call of Abraham (Gen 12) → Joseph in Egypt (Gen 37-50).',
    reference: 'Genesis 1 - 50',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Bible Timeline',
    level: 1,
    stage: 6,
    timeLimit: 40,
    xpReward: 250,
    points: 250,
  },
  {
    id: 'time-002',
    question: 'Arrange the generations of the Patriarchs in chronological sequence:',
    type: 'timeline',
    timelineItems: [
      { id: 'p1', title: 'Abraham covenants with God', order: 1 },
      { id: 'p2', title: 'Isaac is born to Sarah in old age', order: 2 },
      { id: 'p3', title: 'Jacob flees to Laban and father 12 sons', order: 3 },
      { id: 'p4', title: 'Joseph is sold into Egypt and elevated by Pharaoh', order: 4 },
    ],
    correctAnswer: ['p1', 'p2', 'p3', 'p4'],
    explanation: 'The Patriarchal lineage flows through Abraham → Isaac → Jacob → Joseph.',
    reference: 'Genesis 12 - 50',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Bible Timeline',
    level: 1,
    stage: 6,
    timeLimit: 30,
    xpReward: 200,
    points: 200,
  },
  // BIBLE SORT (Stage 1-7)
  {
    id: 'sort-001',
    question: 'Sort the following biblical figures into whether they lived BEFORE or AFTER the Great Flood of Noah:',
    type: 'category_sort',
    sortCategories: [
      { id: 'cat-pre', title: 'Pre-Flood (Antediluvian)' },
      { id: 'cat-post', title: 'Post-Flood' }
    ],
    sortItems: [
      { id: 's1', text: 'Adam & Eve', categoryId: 'cat-pre' },
      { id: 's2', text: 'Enoch (walked with God)', categoryId: 'cat-pre' },
      { id: 's3', text: 'Methuselah', categoryId: 'cat-pre' },
      { id: 's4', text: 'Abraham', categoryId: 'cat-post' },
      { id: 's5', text: 'Isaac & Jacob', categoryId: 'cat-post' },
      { id: 's6', text: 'Joseph', categoryId: 'cat-post' }
    ],
    correctAnswer: 'matched',
    explanation: 'Adam, Enoch, and Methuselah lived prior to the Flood (Genesis 1-5). Abraham, Isaac, Jacob, and Joseph lived after the Flood and the dispersion of Babel (Genesis 11-50).',
    reference: 'Genesis 1 - 50',
    difficulty: 'medium',
    category: 'Patriarchs',
    level: 1,
    stage: 7,
    timeLimit: 45,
    xpReward: 280,
    points: 280,
  },

  // ==========================================
  // LEVEL 2: THE JOURNEY (EXODUS & WILDERNESS)
  // ==========================================
  {
    id: 'exo-001',
    question: 'When Moses asked God what His name was at the burning bush, how did God identify Himself?',
    type: 'multiple_choice',
    options: ['"I AM WHO I AM"', '"The Lord of Hosts"', '"The Ancient of Days"', '"The God of the Mountains"'],
    correctAnswer: '"I AM WHO I AM"',
    explanation: 'God said to Moses, "I AM WHO I AM. This is what you are to say to the Israelites: \'I AM has sent me to you.\'"',
    reference: 'Exodus 3:14',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Exodus',
    level: 2,
    stage: 1,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'exo-002',
    question: 'What was the tenth and final plague brought upon Egypt before Pharaoh released the Israelites?',
    type: 'multiple_choice',
    options: ['Plague of Locusts', 'Death of the Firstborn', 'Darkness for three days', 'Water turned to blood'],
    correctAnswer: 'Death of the Firstborn',
    explanation: 'At midnight the Lord struck down all the firstborn in Egypt, from the firstborn of Pharaoh to the firstborn of the prisoner, prompting Pharaoh to let Israel go.',
    reference: 'Exodus 12:29-31',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Exodus',
    level: 2,
    stage: 2,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'exo-003',
    question: 'What miraculous food did God rain down from heaven each morning to sustain the Israelites in the desert for 40 years?',
    type: 'multiple_choice',
    options: ['Manna', 'Figs', 'Pomegranates', 'Honeycombs'],
    correctAnswer: 'Manna',
    explanation: 'The people of Israel called the bread manna. It was white like coriander seed and tasted like wafers made with honey.',
    reference: 'Exodus 16:31',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Exodus',
    level: 2,
    stage: 2,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'exo-004',
    question: 'Which of the Ten Commandments is the first commandment with a promise attached?',
    type: 'multiple_choice',
    options: [
      'Honor your father and your mother',
      'Remember the Sabbath day by keeping it holy',
      'You shall not murder',
      'You shall have no other gods before me'
    ],
    correctAnswer: 'Honor your father and your mother',
    explanation: '"Honor your father and your mother, so that you may live long in the land the Lord your God is giving you." (Exodus 20:12, Ephesians 6:2).',
    reference: 'Exodus 20:12, Ephesians 6:2',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Exodus',
    level: 2,
    stage: 4,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'who-exo-1',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was placed in a papyrus basket coated with tar and pitch in the Nile river as an infant.',
      'Pharaoh’s daughter found me, had pity on me, and raised me as her own son.',
      'I fled to Midian after killing an Egyptian taskmaster and tended sheep for Jethro.',
      'God spoke to me from a burning bush that did not burn up and sent me to deliver Israel.'
    ],
    options: ['Aaron', 'Moses', 'Joshua', 'Caleb'],
    correctAnswer: 'Moses',
    explanation: 'Moses led the people of Israel out of Egypt, received the Law on Mount Sinai, and spoke with God face to face as with a friend.',
    reference: 'Exodus 2:1-10, Exodus 3:1-10, Exodus 33:11',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Exodus',
    level: 2,
    stage: 5,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },

  // ==========================================
  // LEVEL 3: KINGS & KINGDOMS
  // ==========================================
  {
    id: 'kng-001',
    question: 'What weapon did young David use to defeat the Philistine champion Goliath of Gath?',
    type: 'multiple_choice',
    options: ['A sling and five smooth stones', 'King Saul’s bronze sword', 'A bronze spear', 'A battle ax'],
    correctAnswer: 'A sling and five smooth stones',
    explanation: 'David took his staff in his hand, chose five smooth stones from the stream, put them in the pouch of his shepherd’s bag and, with his sling in his hand, approached the Philistine.',
    reference: '1 Samuel 17:40-50',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Kings',
    level: 3,
    stage: 1,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'kng-002',
    question: 'When God appeared to King Solomon in a dream at Gibeon and asked what He should give him, what did Solomon request?',
    type: 'multiple_choice',
    options: ['A discerning heart and wisdom to govern the people', 'Long life and riches', 'The death of all his enemies', 'Unconquerable armies'],
    correctAnswer: 'A discerning heart and wisdom to govern the people',
    explanation: 'Solomon asked: "Give your servant a discerning heart to govern your people and to distinguish between right and wrong." God was pleased and granted him unmatched wisdom plus wealth and honor.',
    reference: '1 Kings 3:9-13',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Kings',
    level: 3,
    stage: 3,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'kng-003',
    question: 'How did God reveal His presence to Elijah at Mount Horeb after the strong wind, the earthquake, and the fire passed by?',
    type: 'multiple_choice',
    options: ['In a gentle whisper / still small voice', 'In a pillar of blazing cloud', 'In a clap of thunder', 'In an angelic trumpet'],
    correctAnswer: 'In a gentle whisper / still small voice',
    explanation: 'After the wind, earthquake, and fire, the Lord was not in them—and after the fire came a gentle whisper (still small voice). When Elijah heard it, he pulled his cloak over his face.',
    reference: '1 Kings 19:11-13',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Prophets',
    level: 3,
    stage: 5,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'who-kng-1',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was the son of Jesse and anointed by the prophet Samuel in Bethlehem while tending sheep.',
      'I played the harp to soothe King Saul when he was tormented by an evil spirit.',
      'Jonathan loved me as his own soul and made a covenant of loyalty with me.',
      'I became the greatest king of Israel and penned many of the beloved Psalms.'
    ],
    options: ['Solomon', 'David', 'Saul', 'Hezekiah'],
    correctAnswer: 'David',
    explanation: 'David was described by God as "a man after my own heart" (Acts 13:22, 1 Samuel 16).',
    reference: '1 Samuel 16:1-13, 1 Samuel 18:1-4',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Kings',
    level: 3,
    stage: 2,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },
  {
    id: 'sort-kng-1',
    question: 'Classify these famous rulers of the divided monarchy into Kings of Judah vs Kings of Northern Israel:',
    type: 'category_sort',
    sortCategories: [
      { id: 'cat-judah', title: 'Kings of Judah (Southern Kingdom)' },
      { id: 'cat-israel', title: 'Kings of Israel (Northern Kingdom)' }
    ],
    sortItems: [
      { id: 'k1', text: 'Hezekiah (Reformed worship & trusted God against Assyria)', categoryId: 'cat-judah' },
      { id: 'k2', text: 'Josiah (Found the Book of the Law & renewed covenant)', categoryId: 'cat-judah' },
      { id: 'k3', text: 'Jehoshaphat (Sent singers ahead of the army)', categoryId: 'cat-judah' },
      { id: 'k4', text: 'Jeroboam I (Set up golden calves at Dan and Bethel)', categoryId: 'cat-israel' },
      { id: 'k5', text: 'Ahab (Married Jezebel and worshiped Baal)', categoryId: 'cat-israel' },
      { id: 'k6', text: 'Jehu (Drove furiously and destroyed house of Ahab)', categoryId: 'cat-israel' }
    ],
    correctAnswer: 'matched',
    explanation: 'Judah retained the Davidic dynasty in Jerusalem with good reforming kings like Hezekiah and Josiah. Northern Israel had dynasties in Samaria led by Jeroboam, Ahab, and Jehu.',
    reference: '1 & 2 Kings',
    difficulty: 'hard',
    category: 'Kings',
    level: 3,
    stage: 7,
    timeLimit: 45,
    xpReward: 300,
    points: 300,
  },

  // ==========================================
  // LEVEL 4: VOICES OF THE PROPHETS
  // ==========================================
  {
    id: 'pro-001',
    question: 'When the prophet Isaiah saw the Lord seated on a throne, high and exalted, what did the seraphim cry out to one another?',
    type: 'multiple_choice',
    options: [
      '"Holy, holy, holy is the Lord Almighty; the whole earth is full of his glory."',
      '"Mighty and glorious is the King of kings forever and ever."',
      '"Great is our Lord, and abundant in power; his understanding is beyond measure."',
      '"Praise the Lord, O my soul, and all that is within me."'
    ],
    correctAnswer: '"Holy, holy, holy is the Lord Almighty; the whole earth is full of his glory."',
    explanation: 'In Isaiah 6:3, the seraphim called to one another: "Holy, holy, holy is the Lord Almighty; the whole earth is full of his glory."',
    reference: 'Isaiah 6:3',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Prophets',
    level: 4,
    stage: 1,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'pro-002',
    question: 'Which Old Testament prophet was thrown into a den of lions for refusing to stop praying to the God of Israel three times a day?',
    type: 'multiple_choice',
    options: ['Jeremiah', 'Daniel', 'Ezekiel', 'Amos'],
    correctAnswer: 'Daniel',
    explanation: 'King Darius was manipulated into signing an edict, but Daniel continued praying at his open window. God sent an angel to shut the lions’ mouths because Daniel was found blameless.',
    reference: 'Daniel 6:10-23',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Prophets',
    level: 4,
    stage: 4,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'ver-pro-1',
    question: 'Complete the beloved verse from Jeremiah:\n\n"\'For I know the plans I have for you,\' declares the Lord, \'plans to prosper you and not to harm you, plans to give you ___ and a ___.\'"',
    type: 'fill_blank',
    options: ['hope; future', 'wealth; kingdom', 'peace; victory', 'joy; strength'],
    correctAnswer: 'hope; future',
    explanation: '"\'For I know the plans I have for you,\' declares the Lord, \'plans to prosper you and not to harm you, plans to give you hope and a future.\'" — Jeremiah 29:11',
    reference: 'Jeremiah 29:11',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Prophets',
    level: 4,
    stage: 2,
    timeLimit: 20,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'who-pro-1',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'God commanded me to go preach repentance to the great city of Nineveh.',
      'Instead of obeying, I boarded a ship to Tarshish to flee from the Lord.',
      'A great storm arose, and the sailors threw me overboard at my own instruction.',
      'The Lord provided a huge fish to swallow me, and I prayed from inside its belly for three days and three nights.'
    ],
    options: ['Hosea', 'Jonah', 'Micah', 'Nahum'],
    correctAnswer: 'Jonah',
    explanation: 'Jonah repented inside the fish, preached in Nineveh, and witnessed an entire empire repent before God in sackcloth and ashes.',
    reference: 'Jonah 1:1 - 3:10',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Prophets',
    level: 4,
    stage: 3,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },

  // ==========================================
  // LEVEL 5: WISDOM & PRAISE (PSALMS, PROVERBS)
  // ==========================================
  {
    id: 'wis-001',
    question: 'Complete the opening line of the immortal Psalm 23:\n\n"The Lord is my shepherd; I shall not ___."',
    type: 'fill_blank',
    options: ['want', 'fear', 'fall', 'stumble'],
    correctAnswer: 'want',
    explanation: '"The Lord is my shepherd; I shall not want. He makes me lie down in green pastures, he leads me beside quiet waters." — Psalm 23:1-2',
    reference: 'Psalm 23:1',
    translation: 'ESV / KJV',
    difficulty: 'easy',
    category: 'Psalms',
    level: 5,
    stage: 1,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'wis-002',
    question: 'According to Proverbs 9:10 and Psalm 111:10, what is the beginning of wisdom?',
    type: 'multiple_choice',
    options: ['The fear of the Lord', 'Reading many books', 'Living a long life', 'Having great wealth'],
    correctAnswer: 'The fear of the Lord',
    explanation: '"The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding." — Proverbs 9:10',
    reference: 'Proverbs 9:10',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Proverbs',
    level: 5,
    stage: 2,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'wis-003',
    question: 'Complete Proverbs 3:5-6:\n\n"Trust in the Lord with all your heart and lean not on your own ___; in all your ways submit to him, and he will make your paths straight."',
    type: 'fill_blank',
    options: ['understanding', 'strength', 'feelings', 'opinion'],
    correctAnswer: 'understanding',
    explanation: '"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight." — Proverbs 3:5-6',
    reference: 'Proverbs 3:5-6',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Proverbs',
    level: 5,
    stage: 2,
    timeLimit: 20,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'who-wis-1',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I lived in the land of Uz and was blameless and upright, fearing God and shunning evil.',
      'In a single day, I lost all my livestock, servants, and ten children, yet I did not sin or charge God with wrongdoing.',
      'Sores broke out over my entire body from head to foot, and my three friends sat in silence with me for seven days.',
      'I declared: "I know that my Redeemer lives, and that in the end he will stand on the earth."'
    ],
    options: ['Job', 'Solomon', 'Asaph', 'Elihu'],
    correctAnswer: 'Job',
    explanation: 'Job persevered through immense suffering, questioned God’s mystery, and received double restoration from the Lord.',
    reference: 'Job 1:1, Job 19:25, Job 42:10-12',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Wisdom',
    level: 5,
    stage: 3,
    timeLimit: 25,
    xpReward: 160,
    points: 160,
  },

  // ==========================================
  // LEVEL 6: THE LIFE OF JESUS (THE GOSPELS)
  // ==========================================
  {
    id: 'jes-001',
    question: 'In what town was Jesus Christ born, fulfilling the prophecy of Micah 5:2?',
    type: 'multiple_choice',
    options: ['Nazareth', 'Bethlehem in Judea', 'Jerusalem', 'Capernaum'],
    correctAnswer: 'Bethlehem in Judea',
    explanation: 'Jesus was born in Bethlehem of Judea during the reign of King Herod, fulfilling Micah 5:2: "Out of you Bethlehem Ephrathah... will come for me one who will be ruler over Israel."',
    reference: 'Matthew 2:1, Micah 5:2',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Life of Jesus',
    level: 6,
    stage: 1,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'jes-002',
    question: 'What was Jesus’s very first recorded miracle in the Gospel of John?',
    type: 'multiple_choice',
    options: ['Turning water into wine at Cana', 'Healing the blind man at Siloam', 'Feeding the 5,000', 'Walking on the Sea of Galilee'],
    correctAnswer: 'Turning water into wine at Cana',
    explanation: 'At a wedding in Cana in Galilee, Jesus turned six stone jars of water into prime wine, revealing His glory and His disciples believed in Him.',
    reference: 'John 2:1-11',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Miracles',
    level: 6,
    stage: 4,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'jes-003',
    question: 'For how many days and nights did Jesus fast in the Judean wilderness before being tempted by the devil?',
    type: 'multiple_choice',
    options: ['7 days', '12 days', '40 days', '70 days'],
    correctAnswer: '40 days',
    explanation: 'After fasting forty days and forty nights, Jesus was hungry, and answered every temptation of the tempter with: "It is written..."',
    reference: 'Matthew 4:1-11',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Life of Jesus',
    level: 6,
    stage: 2,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'ver-jes-1',
    question: 'Complete the beloved verse of John 3:16:\n\n"For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have ___ life."',
    type: 'fill_blank',
    options: ['eternal', 'peaceful', 'happy', 'earthly'],
    correctAnswer: 'eternal',
    explanation: '"For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." — John 3:16',
    reference: 'John 3:16',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Salvation',
    level: 6,
    stage: 1,
    timeLimit: 15,
    xpReward: 120,
    points: 120,
  },
  {
    id: 'wsi-jes-1',
    question: 'Who said this when Jesus asked His disciples, "Who do you say I am?"\n\n"You are the Messiah, the Son of the living God."',
    type: 'quote',
    options: ['Simon Peter', 'John the Beloved', 'James', 'Thomas'],
    correctAnswer: 'Simon Peter',
    explanation: 'Simon Peter answered, "You are the Messiah, the Son of the living God." Jesus replied, "Blessed are you, Simon son of Jonah, for this was not revealed to you by flesh and blood, but by my Father in heaven."',
    reference: 'Matthew 16:15-17',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Disciples',
    level: 6,
    stage: 3,
    timeLimit: 18,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'time-jes-1',
    question: 'Arrange the events of Holy Week / Passion Week in chronological sequence:',
    type: 'timeline',
    timelineItems: [
      { id: 'pw1', title: 'Triumphal Entry into Jerusalem on a donkey (Palm Sunday)', order: 1 },
      { id: 'pw2', title: 'Cleansing of the Temple courts', order: 2 },
      { id: 'pw3', title: 'The Last Supper and washing the disciples’ feet', order: 3 },
      { id: 'pw4', title: 'Agony and prayer in the Garden of Gethsemane', order: 4 },
      { id: 'pw5', title: 'The Resurrection on the third day morning', order: 5 },
    ],
    correctAnswer: ['pw1', 'pw2', 'pw3', 'pw4', 'pw5'],
    explanation: 'Passion Week proceeds from Palm Sunday → Cleansing Temple → Last Supper (Passover) → Gethsemane & Trials → Crucifixion & Empty Tomb Resurrection.',
    reference: 'Matthew 21-28, Mark 11-16, Luke 19-24, John 12-20',
    translation: 'NIV',
    difficulty: 'medium',
    category: 'Bible Timeline',
    level: 6,
    stage: 6,
    timeLimit: 40,
    xpReward: 260,
    points: 260,
  },
  {
    id: 'sort-jes-1',
    question: 'Sort these famous Parables of Jesus by their primary themes:',
    type: 'category_sort',
    sortCategories: [
      { id: 'cat-lost', title: 'Parables of the Lost & Grace' },
      { id: 'cat-readiness', title: 'Parables of Readiness & Judgment' }
    ],
    sortItems: [
      { id: 'par1', text: 'The Prodigal Son', categoryId: 'cat-lost' },
      { id: 'par2', text: 'The Lost Sheep & Lost Coin', categoryId: 'cat-lost' },
      { id: 'par3', text: 'The Ten Virgins with Lamps', categoryId: 'cat-readiness' },
      { id: 'par4', text: 'The Talents / Minas', categoryId: 'cat-readiness' },
      { id: 'par5', text: 'The Wheat and Tares (Weeds)', categoryId: 'cat-readiness' },
      { id: 'par6', text: 'The Good Samaritan', categoryId: 'cat-lost' }
    ],
    correctAnswer: 'matched',
    explanation: 'Jesus used parables of lost things (Luke 15) to demonstrate God’s joy over one sinner repenting, and parables of virgins and talents (Matthew 25) to teach vigilance and faithfulness until His return.',
    reference: 'Luke 15, Matthew 25',
    difficulty: 'hard',
    category: 'Parables',
    level: 6,
    stage: 7,
    timeLimit: 45,
    xpReward: 320,
    points: 320,
  },

  // ==========================================
  // LEVEL 7: THE EARLY CHURCH (ACTS)
  // ==========================================
  {
    id: 'act-001',
    question: 'What visible and audible manifestations occurred on the Day of Pentecost when the Holy Spirit filled the believers in Jerusalem?',
    type: 'multiple_choice',
    options: [
      'A sound like a violent rushing wind and tongues of fire resting on each of them',
      'An earthquake and a pillar of cloud',
      'A voice like thunder and a dove descending',
      'A bright light that blinded the entire city'
    ],
    correctAnswer: 'A sound like a violent rushing wind and tongues of fire resting on each of them',
    explanation: 'Suddenly a sound like the blowing of a violent wind came from heaven and filled the whole house. They saw what seemed to be tongues of fire that separated and came to rest on each of them.',
    reference: 'Acts 2:2-3',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Acts',
    level: 7,
    stage: 1,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'act-002',
    question: 'Who was the first Christian martyr recorded in the Book of Acts, who saw Jesus standing at the right hand of God as he was stoned?',
    type: 'multiple_choice',
    options: ['Stephen', 'James son of Zebedee', 'Philip', 'Barnabas'],
    correctAnswer: 'Stephen',
    explanation: 'Stephen, full of the Holy Spirit, looked up to heaven and saw the glory of God, and Jesus standing at the right hand of God, praying: "Lord Jesus, receive my spirit... do not hold this sin against them."',
    reference: 'Acts 7:55-60',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Acts',
    level: 7,
    stage: 2,
    timeLimit: 15,
    xpReward: 130,
    points: 130,
  },
  {
    id: 'who-act-1',
    question: 'Who am I?',
    type: 'clues',
    clues: [
      'I was a Pharisee of Pharisees, born in Tarsus of Cilicia, educated under Gamaliel.',
      'I breathed murderous threats against the Lord’s disciples and approved Stephen’s death.',
      'A light from heaven flashed around me on the road to Damascus, and Jesus spoke to me.',
      'I became the Apostle to the Gentiles, planted churches across the Roman Empire, and wrote 13 New Testament letters.'
    ],
    options: ['Peter', 'Paul (Saul of Tarsus)', 'Barnabas', 'Silas'],
    correctAnswer: 'Paul (Saul of Tarsus)',
    explanation: 'Paul was transformed on the Damascus road from a fierce persecutor of the church into the Apostle to the Gentiles.',
    reference: 'Acts 9:1-19, Acts 22:3-16',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Paul',
    level: 7,
    stage: 3,
    timeLimit: 25,
    xpReward: 150,
    points: 150,
  },

  // ==========================================
  // LEVEL 8: LETTERS OF FAITH (THE EPISTLES)
  // ==========================================
  {
    id: 'epi-001',
    question: 'Which of the following is listed as the Fruit of the Spirit in Galatians 5:22-23?',
    type: 'multiple_choice',
    options: [
      'Love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control',
      'Prophecy, tongues, miracles, healing, wisdom and knowledge',
      'Prosperity, fame, honor, riches, and victory',
      'Fasting, sacrifice, ritual washing, and tithes'
    ],
    correctAnswer: 'Love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control',
    explanation: '"But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law." — Galatians 5:22-23',
    reference: 'Galatians 5:22-23',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Christian Living',
    level: 8,
    stage: 2,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'ver-epi-1',
    question: 'Complete Ephesians 2:8-9:\n\n"For it is by ___ you have been saved, through ___; and this is not from yourselves, it is the gift of God—not by works, so that no one can boast."',
    type: 'fill_blank',
    options: ['grace; faith', 'works; deeds', 'prayer; fasting', 'law; obedience'],
    correctAnswer: 'grace; faith',
    explanation: '"For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God—not by works, so that no one can boast." — Ephesians 2:8-9',
    reference: 'Ephesians 2:8-9',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Salvation',
    level: 8,
    stage: 1,
    timeLimit: 18,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'ver-epi-2',
    question: 'Complete Romans 8:28:\n\n"And we know that in all things God works for the ___ of those who love him, who have been called according to his purpose."',
    type: 'fill_blank',
    options: ['good', 'wealth', 'ease', 'protection'],
    correctAnswer: 'good',
    explanation: '"And we know that in all things God works for the good of those who love him, who have been called according to his purpose." — Romans 8:28',
    reference: 'Romans 8:28',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Faith',
    level: 8,
    stage: 1,
    timeLimit: 18,
    xpReward: 140,
    points: 140,
  },

  // ==========================================
  // LEVEL 9: THE REVELATION
  // ==========================================
  {
    id: 'rev-001',
    question: 'On which island was the Apostle John when he received the Revelation of Jesus Christ?',
    type: 'multiple_choice',
    options: ['Patmos', 'Crete', 'Cyprus', 'Malta'],
    correctAnswer: 'Patmos',
    explanation: '"I, John, your brother and companion in the suffering and kingdom and patient endurance... was on the island of Patmos because of the word of God and the testimony of Jesus." — Revelation 1:9',
    reference: 'Revelation 1:9',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Revelation',
    level: 9,
    stage: 1,
    timeLimit: 15,
    xpReward: 140,
    points: 140,
  },
  {
    id: 'ver-rev-1',
    question: 'Complete Revelation 21:4 describing the New Jerusalem:\n\n"\'He will wipe every tear from their eyes. There will be no more ___\' or mourning or crying or pain, for the old order of things has passed away."',
    type: 'fill_blank',
    options: ['death', 'sin', 'night', 'hunger'],
    correctAnswer: 'death',
    explanation: '"\'He will wipe every tear from their eyes. There will be no more death\' or mourning or crying or pain, for the old order of things has passed away." — Revelation 21:4',
    reference: 'Revelation 21:4',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Revelation',
    level: 9,
    stage: 5,
    timeLimit: 18,
    xpReward: 150,
    points: 150,
  },
  {
    id: 'wsi-rev-1',
    question: 'Who speaks these closing words in the final chapter of the Bible?\n\n"Look, I am coming soon! My reward is with me, and I will give to each person according to what they have done. I am the Alpha and the Omega, the First and the Last, the Beginning and the End."',
    type: 'quote',
    options: ['Jesus Christ', 'John the Apostle', 'The Archangel Michael', 'The Angel Gabriel'],
    correctAnswer: 'Jesus Christ',
    explanation: 'Jesus speaks the climactic declaration of Scripture in Revelation 22:12-13, confirming His imminent return and sovereign eternal reign.',
    reference: 'Revelation 22:12-13',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Revelation',
    level: 9,
    stage: 4,
    timeLimit: 18,
    xpReward: 150,
    points: 150,
  },

  // ==========================================
  // LEVEL 10 / MASTER CHALLENGE GAUNTLET
  // ==========================================
  {
    id: 'mst-001',
    question: 'How many total books are in the standard Protestant Bible canon (Old and New Testaments combined)?',
    type: 'multiple_choice',
    options: ['66 books (39 OT, 27 NT)', '70 books (40 OT, 30 NT)', '60 books (30 OT, 30 NT)', '73 books (46 OT, 27 NT)'],
    correctAnswer: '66 books (39 OT, 27 NT)',
    explanation: 'The Protestant canon contains 66 inspired books: 39 in the Old Testament and 27 in the New Testament.',
    reference: 'Biblical Canon / 2 Timothy 3:16',
    translation: 'General',
    difficulty: 'easy',
    category: 'Bible Books',
    level: 10,
    stage: 1,
    timeLimit: 15,
    xpReward: 180,
    points: 180,
  },
  {
    id: 'mst-002',
    question: 'What is the shortest verse in the entire English Bible (KJV / ESV / NIV)?',
    type: 'multiple_choice',
    options: ['"Jesus wept." (John 11:35)', '"Pray without ceasing." (1 Thessalonians 5:17)', '"Rejoice always." (1 Thessalonians 5:16)', '"Remember Lot\'s wife." (Luke 17:32)'],
    correctAnswer: '"Jesus wept." (John 11:35)',
    explanation: 'John 11:35 consists of just two words and 9 letters in English: "Jesus wept." It captures Jesus’s profound compassion at the tomb of Lazarus.',
    reference: 'John 11:35',
    translation: 'NIV',
    difficulty: 'easy',
    category: 'Life of Jesus',
    level: 10,
    stage: 1,
    timeLimit: 15,
    xpReward: 180,
    points: 180,
  },
  {
    id: 'mst-003',
    question: 'In which Old Testament book does the name of God (Yahweh or Elohim) never explicitly appear, yet His sovereign providence is evident throughout?',
    type: 'multiple_choice',
    options: ['Esther', 'Ruth', 'Song of Solomon', 'Ecclesiastes'],
    correctAnswer: 'Esther',
    explanation: 'The Book of Esther never explicitly mentions God’s name, yet His divine orchestration of events to preserve the Jewish people through Queen Esther and Mordecai is unmistakable.',
    reference: 'Book of Esther',
    translation: 'NIV',
    difficulty: 'hard',
    category: 'Bible Books',
    level: 10,
    stage: 1,
    timeLimit: 15,
    xpReward: 200,
    points: 200,
  },
  {
    id: 'sort-mst-1',
    question: 'Sort the following New Testament Epistles into Pauline Epistles vs General (Catholic) Epistles:',
    type: 'category_sort',
    sortCategories: [
      { id: 'cat-paul', title: 'Pauline Epistles' },
      { id: 'cat-general', title: 'General Epistles' }
    ],
    sortItems: [
      { id: 'e1', text: 'Romans & Galatians', categoryId: 'cat-paul' },
      { id: 'e2', text: '1 & 2 Corinthians', categoryId: 'cat-paul' },
      { id: 'e3', text: 'Philippians & Colossians', categoryId: 'cat-paul' },
      { id: 'e4', text: 'James (Faith without works is dead)', categoryId: 'cat-general' },
      { id: 'e5', text: '1 & 2 Peter (Living hope in trials)', categoryId: 'cat-general' },
      { id: 'e6', text: '1, 2, 3 John & Jude', categoryId: 'cat-general' }
    ],
    correctAnswer: 'matched',
    explanation: 'Paul wrote 13 specific letters to churches and associates (Romans to Philemon). The General Epistles (Hebrews, James, Peter, John, Jude) were written to the broader universal church.',
    reference: 'New Testament Canon',
    difficulty: 'expert',
    category: 'Epistles',
    level: 10,
    stage: 5,
    timeLimit: 45,
    xpReward: 400,
    points: 400,
  },
];
