import { Relic } from '@/types/game';

export const MASTER_RELICS: Relic[] = [
  {
    id: 'relic-shield-faith',
    name: 'Shield of Faith',
    title: 'The Quencher of Fiery Darts',
    icon: 'Shield',
    description: 'Forged in Ephesians 6:16. Extinguishes all fiery darts of the adversary.',
    perkDescription: 'Passively protects your life and streak from your FIRST wrong answer in every round.',
    perkType: 'shield',
    cost: 300,
    rarity: 'rare',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'relic-staff-moses',
    name: 'Staff of the Exodus',
    title: 'The Miracle Rod of Sinai',
    icon: 'Flame',
    description: 'The rod with which Moses parted the Red Sea and struck the rock for water.',
    perkDescription: 'Adds +5 extra seconds to the countdown timer on EVERY single question.',
    perkType: 'time_boost',
    cost: 400,
    rarity: 'rare',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'relic-breastplate-urim',
    name: 'Breastplate of Urim',
    title: 'Light & Perfection of the High Priest',
    icon: 'Sparkles',
    description: 'The twelve sacred stones of Aaron reflecting divine illumination.',
    perkDescription: 'Grants 1 FREE 50/50 Wisdom Strike reveal per stage automatically.',
    perkType: 'free_hint',
    cost: 500,
    rarity: 'epic',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'relic-trumpet-gideon',
    name: 'Trumpet of Gideon',
    title: 'The Cry of the 300',
    icon: 'Zap',
    description: 'The shofar sounded in the dark that put the Midianite army to flight.',
    perkDescription: 'CRITICAL STRIKE: Answering correctly under 3 seconds awards a massive 2.5x score bonus!',
    perkType: 'critical_strike',
    cost: 650,
    rarity: 'epic',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'relic-scroll-isaiah',
    name: 'Scroll of the Prophet Isaiah',
    title: 'The Golden Manuscript of Hope',
    icon: 'Scroll',
    description: 'Contains majestic prophecies of the Suffering Servant and the New Creation.',
    perkDescription: 'Boosts your combo streak score multiplier by an additional +50% on every question.',
    perkType: 'combo_boost',
    cost: 800,
    rarity: 'legendary',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'relic-harp-david',
    name: 'Harp of David',
    title: 'The Melody of Deliverance',
    icon: 'Music',
    description: 'Played by the shepherd boy in Saul’s court to drive away evil spirits.',
    perkDescription: 'Grants +50% bonus XP on all correct answers and stage completions.',
    perkType: 'xp_boost',
    cost: 750,
    rarity: 'legendary',
    unlocked: false,
    equipped: false,
  },
];
